name: 'Checks'
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  checks:
    name: Lint & Test
    runs-on: ubuntu-latest
    permissions:
      checks: write
    steps:
      - uses: pnpm/action-setup@v2
        with:
          version: ^8
          
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm run lint

      # - name: Test
      #   run: npm run test:ci

      # - name: Test Report
      #   uses: dorny/test-reporter@v1
      #   if: success() || failure()
      #   with:
      #     reporter: jest-junit
      #     path: junit.xml
      #     name: Unit Tests
